site_name: My Docs
theme:
  name: material
  font:
    text: "Source Sans 3"
    code: "JetBrains Mono"
  palette:
    - scheme: default
      primary: indigo
      accent: amber
    - scheme: slate
      primary: blue
      accent: lime
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.integrate
    - content.code.copy
    - search.suggest
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
# extra_css:
  # - css/custom.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - Ekstremum Funkcji: extremum.md
  - Styczna: styczna.html